In [31]:
import pandas as pd

In [32]:
df=pd.read_csv('employee_data.csv')

In [33]:
df.columns

Index(['emp_id', 'full_name', 'age', 'gender', 'department', 'salary',
       'join_date', 'exp_years', 'emp_status'],
      dtype='object')

In [34]:
df

,emp_id,full_name,age,gender,department,salary,join_date,exp_years,emp_status
0,101,John A. Smith,28.0,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33.0,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent

In [35]:
#1.Rename Columns:
d={'full_name':'name',
  'emp_id':'employee_id',
  'emp_status':'employment_id'}
df.rename(columns=d,inplace=True)
df

,employee_id,name,age,gender,department,salary,join_date,exp_years,employment_id
0,101,John A. Smith,28.0,male,Sales,45000.0,2017-08-19,5.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
2,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,52000.0,2016-03-11,8.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,65000.0,NaN,6.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
6,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,NaN,2015-07-01,12.0,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,58000.0,2019-01-10,4.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent
10,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,75000.0,2014-09-21,NaN,permanent
12,108,Brian P. McDonald,33.0,Male,HR,48000.0,2017-04-15,6.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,55000.0,2020-05-30,3.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,90000.0,2010-02-23,14.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,50000.0,2018-11-03,NaN,permanent

In [36]:
#2. Rearrange Columns:
df=df[df.columns[[0,1,2,3,4,6,7,5,8]]]
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.0,male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,Male,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,Female,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,Male,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,Female,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,female,Marketing,2018-11-03,NaN,50000.0,permanent

In [37]:
#3. Update Column Values(Mapping):
d={'male':'Male','female':'Female'}
df['gender']=df['gender'].map(d)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.0,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,Female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,NaN,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [38]:
#4.Remove Unwanted Characters
df['name']=df['name'].str.strip()
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.0,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.0,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.0,Female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.0,NaN,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.0,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.0,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.0,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.0,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.0,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,NaN,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [39]:
#7. Handle Missing Values:
#Fill missing values in the age column with the average age of the employees.
df['age']=df['age'].fillna(df['age'].mean())
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.000000,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.000000,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.000000,Female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.000000,NaN,IT,2015-07-01,12.0,NaN,permanent
8,106,Priya Ghosh,31.000000,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.000000,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.000000,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.000000,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [40]:
# Fill missing values in the salary column with the median salary
df['salary']=df['salary'].fillna(df['salary'].median())
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.000000,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.000000,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.000000,Female,R&D,NaN,6.0,65000.0,contract
5,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.000000,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31.000000,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.000000,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.000000,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.000000,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [41]:
# For missing join_date, use forward fill (ffill).
df['join_date']=df['join_date'].fillna(method='ffill')
df

<ipython-input-41-9b442ca446d6>:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['join_date']=df['join_date'].fillna(method='ffill')

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28.000000,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35.000000,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29.000000,Female,R&D,2016-03-11,6.0,65000.0,contract
5,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42.000000,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31.000000,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39.000000,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33.000000,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26.000000,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45.000000,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36.916667,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [42]:
#5.Change Data Type:
# Convert the age column to integer type,
df['age']=df['age'].astype(int)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29,Female,R&D,2016-03-11,6.0,65000.0,contract
5,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [43]:
# the salary column to float type.
df['salary']=df['salary'].astype(float)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35,Male,HR,2016-03-11,8.0,52000.0,NaN
4,104,Emily Jackson-Smith,29,Female,R&D,2016-03-11,6.0,65000.0,contract
5,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [44]:
#6. Replace Specific Values:
# In the employment_status column, replace missing values with 'contract'.
df['employment_id']=df['employment_id'].fillna('contract')
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35,Male,HR,2016-03-11,8.0,52000.0,contract
4,104,Emily Jackson-Smith,29,Female,R&D,2016-03-11,6.0,65000.0,contract
5,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
6,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
7,105,Samuel L. Jackson,42,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000.0,contract
9,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
10,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
11,107,Susan M. Thompson,39,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,IT,2020-05-30,3.0,55000.0,contract
14,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
15,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent

In [45]:
#8.Remove Duplicates:
# Ensure there are no duplicate rows in the dataset.
df.drop_duplicates(inplace=True)
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35,Male,HR,2016-03-11,8.0,52000.0,contract
4,104,Emily Jackson-Smith,29,Female,R&D,2016-03-11,6.0,65000.0,contract
7,105,Samuel L. Jackson,42,NaN,IT,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000.0,contract
11,107,Susan M. Thompson,39,NaN,IT,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,HR,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,IT,2020-05-30,3.0,55000.0,contract

In [46]:
#9.Apply String Function:
# Capitalize the first letter of each word in the department column.
df['department']=df['department'].str.capitalize()
df

,employee_id,name,age,gender,department,join_date,exp_years,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,5.0,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,NaN,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,14.0,90000.0,permanent
3,103,Mark O'Donnell,35,Male,Hr,2016-03-11,8.0,52000.0,contract
4,104,Emily Jackson-Smith,29,Female,R&d,2016-03-11,6.0,65000.0,contract
7,105,Samuel L. Jackson,42,NaN,It,2015-07-01,12.0,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,4.0,58000.0,contract
11,107,Susan M. Thompson,39,NaN,It,2014-09-21,NaN,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,Hr,2017-04-15,6.0,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,It,2020-05-30,3.0,55000.0,contract

In [47]:
#10.Drop Unwanted Columns:
# Remove the exp_years column from the dataset.
df.drop('exp_years',axis=1,inplace=True)
df

,employee_id,name,age,gender,department,join_date,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,50000.0,permanent
2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,90000.0,permanent
3,103,Mark O'Donnell,35,Male,Hr,2016-03-11,52000.0,contract
4,104,Emily Jackson-Smith,29,Female,R&d,2016-03-11,65000.0,contract
7,105,Samuel L. Jackson,42,NaN,It,2015-07-01,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000.0,contract
11,107,Susan M. Thompson,39,NaN,It,2014-09-21,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,Hr,2017-04-15,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,It,2020-05-30,55000.0,contract

In [48]:
#11. Remove Specific Rows:
# Drop rows where salary is above 80,000 to focus on mid-level employees
df.drop(df[df['salary']>80000].index)

,employee_id,name,age,gender,department,join_date,salary,employment_id
0,101,John A. Smith,28,Male,Sales,2017-08-19,45000.0,permanent
1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,50000.0,permanent
3,103,Mark O'Donnell,35,Male,Hr,2016-03-11,52000.0,contract
4,104,Emily Jackson-Smith,29,Female,R&d,2016-03-11,65000.0,contract
7,105,Samuel L. Jackson,42,NaN,It,2015-07-01,55000.0,permanent
8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000.0,contract
11,107,Susan M. Thompson,39,NaN,It,2014-09-21,75000.0,permanent
12,108,Brian P. McDonald,33,NaN,Hr,2017-04-15,48000.0,permanent
13,109,Sophia Y. Richardson,26,NaN,It,2020-05-30,55000.0,contract

In [49]:
#12.Reset Index:
#After cleaning, reset the index of the DataFrame
df.reset_index(inplace=True)
df

,index,employee_id,name,age,gender,department,join_date,salary,employment_id
0,0,101,John A. Smith,28,Male,Sales,2017-08-19,45000.0,permanent
1,1,102,Sarah-Louise James,36,Female,Marketing,2018-11-03,50000.0,permanent
2,2,110,Rajesh Kumar,45,Male,Sales,2010-02-23,90000.0,permanent
3,3,103,Mark O'Donnell,35,Male,Hr,2016-03-11,52000.0,contract
4,4,104,Emily Jackson-Smith,29,Female,R&d,2016-03-11,65000.0,contract
5,7,105,Samuel L. Jackson,42,NaN,It,2015-07-01,55000.0,permanent
6,8,106,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000.0,contract
7,11,107,Susan M. Thompson,39,NaN,It,2014-09-21,75000.0,permanent
8,12,108,Brian P. McDonald,33,NaN,Hr,2017-04-15,48000.0,permanent
9,13,109,Sophia Y. Richardson,26,NaN,It,2020-05-30,55000.0,contract

In [50]:
#13. Set Column as Index:
#Set the employee_id as the index of the DataFrame
df.set_index('employee_id',inplace=True)
df

,index,name,age,gender,department,join_date,salary,employment_id
employee_id,,,,,,,,
101,0,John A. Smith,28,Male,Sales,2017-08-19,45000.0,permanent
102,1,Sarah-Louise James,36,Female,Marketing,2018-11-03,50000.0,permanent
110,2,Rajesh Kumar,45,Male,Sales,2010-02-23,90000.0,permanent
103,3,Mark O'Donnell,35,Male,Hr,2016-03-11,52000.0,contract
104,4,Emily Jackson-Smith,29,Female,R&d,2016-03-11,65000.0,contract
105,7,Samuel L. Jackson,42,NaN,It,2015-07-01,55000.0,permanent
106,8,Priya Ghosh,31,NaN,Marketing,2019-01-10,58000.0,contract
107,11,Susan M. Thompson,39,NaN,It,2014-09-21,75000.0,permanent
108,12,Brian P. McDonald,33,NaN,Hr,2017-04-15,48000.0,permanent
109,13,Sophia Y. Richardson,26,NaN,It,2020-05-30,55000.0,contract